# Informações sobre o projeto
app.name = Buscador Zap
app.description = ${app.nome} - Projeto desenvolvido por @guimadois
#URL de busca de dados
app.url-source = http://grupozap-code-challenge.s3-website-us-east-1.amazonaws.com/sources/source-2.json

#Definiçõees boundingBox grupo zap
bounding-box.min-lon = -46.693419
bounding-box.min-lat = -23.568704
bounding-box.max-lon = -46.641146
bounding-box.max-lat = -23.546686

#Definições Zap+
zap.min-rent-price = 3500
zap.min-sale-price = 600000
zap.min-built-square-meter-value = 3500
#10% desconto
zap.bounding-box-multiplier = 0.9 

#Definições Viva Real
viva-real.max-rent-price = 4000
viva-real.max-sale-price = 700000
#50% acréscimo
viva-real.bounding-box-multiplier = 1.5
# % limite do valor do condominio em relação ao aluguel
viva-real.percent-total-price-monthly-condo = 0.3